import styled from "styled-components";

export const Container = styled.div`
 
 .searchICon{
  color:var(--Blue);
  margin-right: 20px;
  display: flex;
  padding:4px;
  margin-top:-2px;

  svg{
    font-size:22px;
  }
  &:hover{
    animation: myAnim 1s ease 0s 1 normal forwards;
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2022-2-25 17:15:28
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation jello-horizontal
 * ----------------------------------------
 */
 
}

@keyframes myAnim {
  0%,
  100% {
    transform: rotate(0deg);
    transform-origin: 50% 50%;
  }

  10% {
    transform: rotate(8deg);
  }

  20%,
  40%,
  60% {
    transform: rotate(-10deg);
  }

  30%,
  50%,
  70% {
    transform: rotate(10deg);
  }

  80% {
    transform: rotate(-8deg);
  }

  90% {
    transform: rotate(8deg);
  }
}
`;


