export const swissDepartementCode = [
  { code: "AG", nom: "Aargau" },
  { code: "AR", nom: "Appenzell Ausserrhoden" },
  { code: "AI", nom: "Appenzell Innerrhoden" },
  { code: "BL", nom: "Basel-Landschaft" },
  { code: "BS", nom: "Basel-Stadt" },
  { code: "BE", nom: "Bern" },
  { code: "FR", nom: "Fribourg" },
  { code: "GE", nom: "Genève" },
  { code: "GL", nom: "Glarus" },
  { code: "GR", nom: "Graubünden" },
  { code: "JU", nom: "Jura" },
  { code: "LU", nom: "Luzern" },
  { code: "NE", nom: "Neuchâtel" },
  { code: "NW", nom: "Nidwalden" },
  { code: "OW", nom: "Obwalden" },
  { code: "SG", nom: "Sankt Gallen" },
  { code: "SH", nom: "Schaffhausen" },
  { code: "SZ", nom: "Schwyz" },
  { code: "SO", nom: "Solothurn" },
  { code: "TG", nom: "Thurgau" },
  { code: "TI", nom: "Ticino" },
  { code: "UR", nom: "Uri" },
  { code: "VS", nom: "Valais" },
  { code: "VD", nom: "Vaud" },
  { code: "ZG", nom: "Zug" },
  { code: "ZH", nom: "Zürich" },
];
