export const swissDepartementCode = [
{code: "CH-AG", nom: "Aargau"},
{code: "CH-AR", nom: "Appenzell Ausserrhoden"},
{code: "CH-AI", nom: "Appenzell Innerrhoden"},
{code: "CH-BL", nom: "Basel-Landschaft"},
{code: "CH-BS", nom: "Basel-Stadt"},
{code: "CH-BE", nom: "Bern"},
{code: "CH-FR", nom: "Fribourg"},
{code: "CH-GE", nom: "Genève"},
{code: "CH-GL", nom: "Glarus"},
{code: "CH-GR", nom: "Graubünden"},
{code: "CH-JU", nom: "Jura"},
{code: "CH-LU", nom: "Luzern"},
{code: "CH-NE", nom: "Neuchâtel"},
{code: "CH-NW", nom: "Nidwalden"},
{code: "CH-OW", nom: "Obwalden"},
{code: "CH-SG", nom: "Sankt Gallen"},
{code: "CH-SH", nom: "Schaffhausen"},
{code: "CH-SZ", nom: "Schwyz"},
{code: "CH-SO", nom: "Solothurn"},
{code: "CH-TG", nom: "Thurgau"	},
{code: "CH-TI", nom: "Ticino"},
{code: "CH-UR", nom: "Uri"},
{code: "CH-VS", nom: "Valais"},
{code: "CH-VD", nom: "Vaud"},
{code: "CH-VS", nom: "Wallis"},
{code: "CH-ZG", nom: "Zug"},
{code: "CH-ZH", nom: "Zürich"}
]